### ISSUE TITLE
RELEASE 1.1.7

### ISSUE THREAD

**Issue by PeterTeng** [PeterTeng/googleit#50]
## WHAT

- [x] Test Unit for developer
- [x] Travis CI test
- [x] Logo in README
- [x] Add github page 
- [x] Makefile for installation

## TODO

- [x] Add `make install` guide on README
- [x]  Update version string
- [x] npm publish
- [x] Check on production
